import Link from 'next/link';
import { notFound } from 'next/navigation';
import { PageHeader } from '@/components/ui/PageHeader';
import { StoreArchiveButton } from '@/modules/stores/components/StoreArchiveButton';
import { storeService } from '@/modules/stores/services/StoreService';
export const dynamic='force-dynamic';
export default async function StoreDetailsPage({params}:{params:Promise<{id:string}>}){let store;try{store=await storeService.getStoreById((await params).id)}catch{notFound()}
 const operations=[...new Map(store.visits.map(v=>[v.operation.id,v.operation])).values()]; const industries=[...new Map(store.visits.map(v=>[v.industry.id,v.industry])).values()]; const promoters=[...new Map(store.visits.map(v=>[v.promoter.id,v.promoter])).values()]; const completed=store.visits.filter(v=>v.status==='REALIZADA'); const last=completed.sort((a,b)=>(b.completedDate||b.scheduledDate).getTime()-(a.completedDate||a.scheduledDate).getTime())[0];
 return <main className="mx-auto w-full max-w-6xl space-y-6 px-4 py-8"><PageHeader category="Lojas" title={store.name} subtitle={`${store.city||'Cidade não informada'} / ${store.state||'UF não informada'}`} actions={<div className="flex gap-2"><Link href={`/dashboard/lojas/${store.id}/editar`} className="rounded-md bg-[#20201f] px-3 py-2 text-xs text-white">Editar</Link><StoreArchiveButton id={store.id} archived={Boolean(store.archivedAt)}/></div>}/>
 <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card label="Visitas realizadas" value={completed.length}/><Card label="Indústrias" value={industries.length}/><Card label="Promotores" value={promoters.length}/><Card label="Última visita" value={last?new Intl.DateTimeFormat('pt-BR').format(last.completedDate||last.scheduledDate):'-'}/></section>
 <section className="grid gap-5 rounded-lg border bg-white p-5 md:grid-cols-2"><Info label="Nome" value={store.name}/><Info label="Código" value={store.code}/><Info label="Endereço" value={store.address}/><Info label="Cidade / UF" value={`${store.city||'-'} / ${store.state||'-'}`}/><Info label="Operação" value={operations.map(x=>x.name).join(', ')}/><Info label="Indústrias atendidas" value={industries.map(x=>x.name).join(', ')}/><Info label="Promotores" value={promoters.map(x=>x.name).join(', ')}/><Info label="Status" value={store.archivedAt?'Arquivada':'Ativa'}/></section>
 </main>}
function Card({label,value}:{label:string;value:string|number}){return <div className="rounded-lg border bg-white p-4"><p className="text-xs text-[#777772]">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div>}; function Info({label,value}:{label:string;value:string|null|undefined}){return <div><dt className="text-xs font-medium text-[#777772]">{label}</dt><dd className="mt-1 text-sm">{value||'-'}</dd></div>}
