import Link from 'next/link';
import { AlertTriangle, ArrowRight, Building2, CheckCircle2, ClipboardCheck, Factory, MapPin, Route, Store, Upload, Users } from 'lucide-react';
import { DashboardOverviewService } from '@/modules/dashboard/DashboardOverviewService';
export const dynamic='force-dynamic';
const status:Record<string,string>={PLANNING:'Planejamento',OPEN:'Aberta',IN_PROGRESS:'Em andamento',FINISHED:'Finalizada',CANCELLED:'Cancelada',ARCHIVED:'Arquivada'};
const date=(value:Date,withTime=false)=>new Intl.DateTimeFormat('pt-BR',withTime?{dateStyle:'short',timeStyle:'short'}:{dateStyle:'short'}).format(value);
export default async function DashboardPage(){const data=await DashboardOverviewService.getData();const last=data.cards.lastImport;const totalVisits=data.cards.planned+data.cards.completed;const progress=totalVisits?Math.round(data.cards.completed/totalVisits*100):0;const kpis=[['Operações',data.cards.operations,Building2],['Promotores',data.cards.promoters,Users],['Lojas',data.cards.stores,Store],['Indústrias',data.cards.industries,Factory],['Planejadas',data.cards.planned,Route],['Realizadas',data.cards.completed,CheckCircle2],['Pendências',data.cards.pending,AlertTriangle],['Conciliações',data.cards.reconciliations,ClipboardCheck]] as const;return <main className="mx-auto w-full max-w-[1500px] space-y-6 px-4 py-7 sm:px-6 lg:px-8 lg:py-9">
<header className="flex flex-col justify-between gap-5 border-b border-[var(--mk-border)] pb-6 md:flex-row md:items-end"><div><p className="mk-label text-[var(--mk-primary)]">Visão executiva</p><h1 className="mt-2 text-3xl font-bold tracking-[-.035em]">Centro de Operações</h1><p className="mt-1.5 max-w-2xl text-sm text-[var(--mk-text-secondary)]">Acompanhe operação, cobertura e execução em uma visão única e objetiva.</p></div><Link href="/dashboard/imports" className="mk-primary-button"><Upload className="h-3.5 w-3.5"/>Nova importação</Link></header>
<section aria-label="Indicadores principais" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">{kpis.map(([label,value,Icon])=><article key={label} className={`mk-kpi ${label==='Pendências'&&Number(value)>0?'border-[color-mix(in_srgb,var(--mk-warning)_36%,var(--mk-border))]':''}`}><div className="flex items-start justify-between gap-2"><div><p className="mk-label">{label}</p><p className="mt-2 text-2xl font-bold tabular-nums">{value}</p></div><span className="mk-kpi-icon"><Icon className="h-4 w-4"/></span></div></article>)}</section>
<div className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><section className="mk-panel p-5"><div className="flex items-start justify-between gap-4"><div><p className="mk-label">Execução de visitas</p><h2 className="mt-1 text-lg font-bold">Planejadas versus realizadas</h2></div><span className="text-2xl font-bold text-[var(--mk-primary)] tabular-nums">{progress}%</span></div><div className="mt-6 h-2.5 overflow-hidden rounded-full bg-[var(--mk-bg-secondary)]"><div className="h-full rounded-full bg-[var(--mk-primary)] transition-all" style={{width:`${progress}%`}}/></div><div className="mt-4 grid grid-cols-3 gap-3 text-xs"><Summary label="Planejadas" value={data.cards.planned}/><Summary label="Realizadas" value={data.cards.completed}/><Summary label="Total acompanhado" value={totalVisits}/></div></section>
<section className="mk-panel p-5"><div className="flex items-start justify-between"><div><p className="mk-label">Última importação</p><h2 className="mt-1 text-lg font-bold">{last?.files[0]?.fileName||'Nenhum arquivo'}</h2></div><Upload className="h-5 w-5 text-[var(--mk-primary)]"/></div>{last?<><p className="mt-3 text-sm text-[var(--mk-text-secondary)]">Processada em {date(last.createdAt,true)}</p><span className="mk-status mk-status-info mt-4">{last.status}</span></>:<p className="mt-4 text-sm text-[var(--mk-text-subtle)]">Envie o primeiro arquivo para iniciar o histórico.</p>}<Link href="/dashboard/importacoes" className="mt-5 inline-flex items-center gap-1 text-xs font-bold text-[var(--mk-primary)]">Ver importações <ArrowRight className="h-3 w-3"/></Link></section></div>
<div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><section className="mk-panel overflow-hidden"><SectionHeader title="Operações recentes" description="Cobertura, equipe e volume das operações" action="/dashboard/operacoes"/><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead><tr>{['Operação','Período','Lojas','Promotores','Visitas','Status'].map(x=><th key={x} className="px-5 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-[var(--mk-border)]">{data.operations.slice(0,6).map(x=><tr key={x.id}><td className="px-5 py-3.5 font-semibold text-[var(--mk-text)]"><Link href={`/dashboard/operacoes/${x.id}`}>{x.name}</Link></td><td className="px-5 py-3.5">{date(x.startsAt)} – {date(x.endsAt)}</td><td className="px-5 py-3.5">{x.stores}</td><td className="px-5 py-3.5">{x.promoters}</td><td className="px-5 py-3.5">{x.visits}</td><td className="px-5 py-3.5"><span className="mk-status mk-status-info">{status[x.status]||x.status}</span></td></tr>)}</tbody></table>{!data.operations.length&&<Empty text="Nenhuma operação cadastrada."/>}</div></section><section className="mk-panel p-5"><div className="flex items-center gap-3"><span className="mk-kpi-icon"><AlertTriangle className="h-4 w-4"/></span><div><p className="mk-label">Atenção necessária</p><h2 className="mt-1 text-lg font-bold">Pendências operacionais</h2></div></div><p className="mt-6 text-4xl font-bold tabular-nums">{data.cards.pending}</p><p className="mt-2 text-sm leading-6 text-[var(--mk-text-secondary)]">Visitas vencidas e evidências que aguardam resolução.</p><Link href="/dashboard/conciliacao" className="mk-secondary-button mt-5 w-full">Abrir conciliação</Link></section></div>
<div className="grid gap-5 lg:grid-cols-3"><Chart title="Visitas por operação" data={data.charts.byOperation}/><Chart title="Visitas por UF" data={data.charts.byState}/><Chart title="Visitas por indústria" data={data.charts.byIndustry}/></div>
<section className="mk-panel overflow-hidden"><SectionHeader title="Últimas atividades" description="Movimentações recentes registradas no sistema"/><div className="divide-y divide-[var(--mk-border)] px-5">{data.activities.slice(0,7).map(x=><div key={x.id} className="grid gap-1 py-3.5 text-xs sm:grid-cols-[110px_minmax(0,1fr)_auto] sm:gap-3"><span className="font-bold text-[var(--mk-info)]">{x.type}</span><span className="truncate text-[var(--mk-text-secondary)]">{x.description}</span><time className="text-[var(--mk-text-subtle)]">{date(x.date,true)}</time></div>)}{!data.activities.length&&<Empty text="Nenhuma atividade registrada."/>}</div></section></main>}
function Summary({label,value}:{label:string;value:number}){return <div><p className="text-[var(--mk-text-subtle)]">{label}</p><p className="mt-1 font-bold tabular-nums text-[var(--mk-text)]">{value}</p></div>}
function SectionHeader({title,description,action}:{title:string;description:string;action?:string}){return <header className="flex items-center justify-between gap-4 border-b border-[var(--mk-border)] px-5 py-4"><div><h2 className="text-sm font-bold">{title}</h2><p className="mt-1 text-xs text-[var(--mk-text-subtle)]">{description}</p></div>{action&&<Link href={action} className="text-xs font-bold text-[var(--mk-primary)]">Ver todas</Link>}</header>}
function Chart({title,data}:{title:string;data:{label:string;value:number}[]}){const max=Math.max(1,...data.map(x=>x.value));return <section className="mk-panel p-5"><h2 className="text-sm font-bold">{title}</h2><div className="mt-5 space-y-3.5">{data.slice(0,6).map(x=><div key={x.label} className="grid grid-cols-[100px_1fr_34px] items-center gap-3 text-xs"><span className="truncate" title={x.label}>{x.label}</span><div className="h-1.5 rounded-full bg-[var(--mk-bg-secondary)]"><div className="h-full rounded-full bg-[var(--mk-primary)]" style={{width:`${x.value/max*100}%`}}/></div><span className="text-right font-mono text-[var(--mk-text-subtle)]">{x.value}</span></div>)}{!data.length&&<Empty text="Sem dados disponíveis."/>}</div></section>}
function Empty({text}:{text:string}){return <p className="py-8 text-center text-sm text-[var(--mk-text-subtle)]">{text}</p>}